version: "3.8"
services:
  balancer:
    build: .
    links:
      - rabbit
    volumes:
    - ./:/project
    command: "python3 main_balancer.py"
  computing:
    build: .
    links:
      - rabbit
    volumes:
    - ./:/project
    command: "python3 main_computing.py"
  rabbit:
    image: "rabbitmq:3-management"
    ports:
    - "5672:5672"  # rabbitmq ports
    - "15672:15672"  # management site ports
